export const Dummy_Data = [
	{
		id: 1,
		category: "sunscreen",
		image: "/images/objects/img1.jpg",
		title: "Garnier",
		price: 18,
	},
	{
		id: 2,
		category: "sunscreen",
		image: "/images/objects/img2.jpg",
		title: "Lotus",
		price: 28,
	},
	{
		id: 3,
		category: "sunscreen",
		image: "/images/objects/img3.jpg",
		title: "Garnbent",
		price: 8,
	},
	{
		id: 4,
		category: "facewash",
		image: "/images/objects/img4.jpg",
		title: "Garnier",
		price: 18,
	},
	{
		id: 5,
		category: "facewash",
		image: "/images/objects/img5.jpg",
		title: "Lgon",
		price: 18,
	},
	{
		id: 6,
		category: "facewash",
		image: "/images/objects/img6.jpg",
		title: "Garr",
		price: 18,
	},
	{
		id: 7,
		category: "facewash",
		image: "/images/objects/img7.jpg",
		title: "Tier",
		price: 18,
	},
	{
		id: 8,
		category: "sunscreen",
		image: "/images/objects/img8.jpg",
		title: "Arnier",
		price: 18,
	},
	{
		id: 9,
		category: "cream",
		image: "/images/objects/img9.jpg",
		title: "Garnier",
		price: 18,
	},
	{
		id: 10,
		category: "cream",
		image: "/images/objects/img10.jpg",
		title: "Garnier",
		price: 58,
	},
	{
		id: 11,
		category: "sunscreen",
		image: "/images/objects/img11.jpg",
		title: "Garnier",
		price: 3,
	},
	{
		id: 12,
		category: "sunscreen",
		image: "/images/objects/img12.jpg",
		title: "Garnier",
		price: 2,
	},
];
